ecb_url = 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml'
cube = '{http://www.ecb.int/vocabulary/2002-08-01/eurofxref}Cube'
symbols = [
  {"symbol": "A$", "cc": "AUD", "name": "Australian dollar"},
  {"symbol": "BGN", "cc": "BGN", "name": "Bulgarian lev"},
  {"symbol": "R$", "cc": "BRL", "name": "Brazilian real"},
  {"symbol": "C$", "cc": "CAD", "name": "Canadian dollar"},
  {"symbol": "Fr.", "cc": "CHF", "name": "Swiss franc"},
  {"symbol": "\u04B0", "cc": "CNY", "name": "Chinese/Yuan renminbi"},
  {"symbol": "K\u010d", "cc": "CZK", "name": "Czech koruna"},
  {"symbol": "Kr", "cc": "DKK", "name": "Danish krone"},
  {"symbol": "\u00a3", "cc": "GBP", "name": "British pound"},
  {"symbol": "HK$", "cc": "HKD", "name": "Hong Kong dollar"},
  {"symbol": "kn", "cc": "HRK", "name": "Croatian kuna"},
  {"symbol": "Ft", "cc": "HUF", "name": "Hungarian forint"},
  {"symbol": "Rp", "cc": "IDR", "name": "Indonesian rupiah"},
  {"symbol": "\u20aa", "cc": "ILS", "name": "Israeli new sheqel"},
  {"symbol": "\u20b9", "cc": "INR", "name": "Indian rupee"},
  {"symbol": "\u00a5", "cc": "JPY", "name": "Japanese yen"},
  {"symbol": "W", "cc": "KRW", "name": "South Korean won"},
  {"symbol": "Mex$", "cc": "MXN", "name": "Mexican peso"},
  {"symbol": "RM", "cc": "MYR", "name": "Malaysian ringgit"},
  {"symbol": "kr", "cc": "NOK", "name": "Norwegian krone"},
  {"symbol": "NZ$", "cc": "NZD", "name": "New Zealand dollar"},
  {"symbol": "\u20b1", "cc": "PHP", "name": "Philippine peso"},
  {"symbol": "z\u0142", "cc": "PLN", "name": "Polish zloty"},
  {"symbol": "L", "cc": "RON", "name": "Romanian leu"},
  {"symbol": "R", "cc": "RUB", "name": "Russian ruble"},
  {"symbol": "kr", "cc": "SEK", "name": "Swedish krona"},
  {"symbol": "S$", "cc": "SGD", "name": "Singapore dollar"},
  {"symbol": "\u0e3f", "cc": "THB", "name": "Thai baht"},
  {"symbol": "TRY", "cc": "TRY", "name": "Turkish new lira"},
  {"symbol": "$", "cc": "USD", "name": "United States dollar"},
  {"symbol": "R", "cc": "ZAR", "name": "South African rand"},
  {"symbol": "€", "cc": "EUR", "name": "EURO"},
]
test_rate = {
    'ZAR': 14.5157,
    'DKK': 7.4401,
    'CZK': 26.598,
    'MXN': 20.605,
    'RUB': 62.065,
    'HRK': 7.432,
    'SGD': 1.5292,
    'IDR': 14490.5,
    'MYR': 4.7225,
    'CNY': 7.4957,
    'JPY': 123.69,
    'GBP': 0.84485,
    'HKD': 8.4594,
    'HUF': 310.57,
    'INR': 69.906,
    'PLN': 4.2242,
    'BGN': 1.9558,
    'PHP': 54.176,
    'RON': 4.549,
    'KRW': 1225.56,
    'AUD': 1.4737,
    'ILS': 3.922,
    'THB': 37.74,
    'NZD': 1.5862,
    'TRY': 3.8921,
    'CHF': 1.0952,
    'CAD': 1.4906,
    'NOK': 9.333,
    'USD': 1.086,
    'BRL': 3.4363,
    'SEK': 9.6478,
    'EUR': 1.0
}
